name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set Environment Variables
        env: 
          # AWS Configuration
          VITE_AWS_REGION: ${{ secrets.VITE_AWS_REGION }}
          VITE_AWS_ACCESS_KEY_ID: ${{ secrets.VITE_AWS_ACCESS_KEY_ID }}
          VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.VITE_AWS_SECRET_ACCESS_KEY }}
          VITE_DYNAMODB_TABLE_NAME: ${{ secrets.VITE_DYNAMODB_TABLE_NAME }}
          # Setting DEBUG Variables
          VITE_USE_DYNAMODB: ${{ vars.VITE_USE_DYNAMODB }}
          VITE_DEBUG_MODE: ${{ vars.VITE_DEBUG_MODE }}
          VITE_LOCAL_STORAGE_PREFIX: ${{ vars.VITE_LOCAL_STORAGE_PREFIX }}
        run: |
          echo "VITE_AWS_REGION=${VITE_AWS_REGION}" >> .env
          echo "VITE_AWS_ACCESS_KEY_ID=${VITE_AWS_ACCESS_KEY_ID}" >> .env
          echo "VITE_AWS_SECRET_ACCESS_KEY=${VITE_AWS_SECRET_ACCESS_KEY}" >> .env
          echo "VITE_DYNAMODB_TABLE_NAME=${VITE_DYNAMODB_TABLE_NAME}" >> .env
          echo "VITE_USE_DYNAMODB=${VITE_USE_DYNAMODB}" >> .env
          echo "VITE_DEBUG_MODE=${VITE_DEBUG_MODE}" >> .env
          echo "VITE_LOCAL_STORAGE_PREFIX=${VITE_LOCAL_STORAGE_PREFIX}" >> .env


      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
